version: '2'
services:

  web:
    container_name: teste-api
    build: docker/dev
    ports:
      - "3333:3333"
      - "3229:9229"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - database

  database:
    container_name: teste-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=108001
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"